# Project information
site_name: The Sun Also Rises.
site_description: Xiao Xu - Homepage
site_author: 'Xiao Xu'
site_url: 'https://looperxx.github.io/'

# Repository
repo_name: 'LooperXX/LooperXX.github.io'
repo_url: 'https://github.com/LooperXX/LooperXX.github.io'

# Copyright
copyright: 'Copyright &copy; 2019 - 2022; Xiao Xu'

# Configuration
theme:
  name: 'material' 
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: 'zh'
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  # font:
  #   text: 'Roboto'
  #   code: 'Roboto Mono'
  # logo:
  #   icon: 'cloud'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/looperXX'
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/looperxx_nlp
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/%E5%95%B8-%E5%BE%90-012456163/'
  disqus: 'https-looperxx-github-io-my-wiki'
  search:
    language: 'jp'
  analytics:
    provider: google
    property: G-CV5JZHXZY8

# Extensions
extra_javascript:
  - javascripts/baidu-tongji.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: looperxx
      repo: looperxx.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

# Page tree
nav:
  - Xiao Xu @ HIT-SCIR: 'index.md'
  - Notes: 
      - 'Normalization' : 'Normalization.md'
      - 'Transfer Learning': 'Transfer Learning.md'
      - 'Attention' : 'Attention.md'
      - 'Machine Reading Comprehension': 'Neural Reading Comprehension and beyond.md'
      - 'NCRF++' : 'Notes on NCRF++.md'
  - CS224n-2019 Notes:
      - 'CS224n-2019 Introduction' : 'CS224n-2019-00-Info.md'
      - 'CS224n-2019 Assignment' : 'CS224n-2019-Assignment.md'
      - '01 Introduction and Word Vectors' : 'CS224n-2019-01-Introduction and Word Vectors.md'
      - '02 Word Vectors 2 and Word Senses' : 'CS224n-2019-02-Word Vectors 2 and Word Senses.md'
      - '03 Word Window Classification,Neural Networks, and Matrix Calculus' : 'CS224n-2019-03-Word Window Classification,Neural Networks, and Matrix Calculus.md'
      - '04 Backpropagation and Computation Graphs' : 'CS224n-2019-04-Backpropagation and Computation Graphs.md'
      - '05 Linguistic Structure Dependency Parsing' : 'CS224n-2019-05-Linguistic Structure Dependency Parsing.md'
      - '06 The probability of a sentence Recurrent Neural Networks and Language Models' : 'CS224n-2019-06-The probability of a sentence Recurrent Neural Networks and Language Models.md'
      - '07 Vanishing Gradients and Fancy RNNs' : 'CS224n-2019-07-Vanishing Gradients and Fancy RNNs.md'
      - '08 Machine Translation, Sequence-to-sequence and Attention' : 'CS224n-2019-08-Machine Translation, Sequence-to-sequence and Attention.md'
      - '09 Practical Tips for Final Projects' : 'CS224n-2019-09-Practical Tips for Final Projects.md'
      - '10 Question Answering and the Default Final Project' : 'CS224n-2019-10-Question Answering and the Default Final Project.md'
      - '11 ConvNets for NLP' : 'CS224n-2019-11-ConvNets for NLP.md'
      - '12 Information from parts of words Subword Models' : 'CS224n-2019-12-Information from parts of words Subword Models.md'
      - '13 Modeling contexts of use Contextual Representations and Pretraining' : 'CS224n-2019-13-Modeling contexts of use Contextual Representations and Pretraining.md'
      - '14 Transformers and Self-Attention For Generative Models' : 'CS224n-2019-14-Transformers and Self-Attention For Generative Models.md'
      - '15 Natural Language Generation' : 'CS224n-2019-15-Natural Language Generation.md'
      - '16 Coreference Resolution' : 'CS224n-2019-16-Coreference Resolution.md'
      - '17 Multitask Learning' : 'CS224n-2019-17-Multitask Learning.md'
      - '18 Tree Recursive Neural Networks, Constituency Parsing, and Sentiment' : 'CS224n-2019-18-Tree Recursive Neural Networks, Constituency Parsing, and Sentiment.md'
      - '19 Safety, Bias, and Fairness' : 'CS224n-2019-19-Safety, Bias, and Fairness.md'
      - '20 The Future of NLP + Deep Learning' : 'CS224n-2019-20-The Future of NLP + Deep Learning.md' 
  - MkDocs Notes:
      - 'Demo' : 'MkDocs_demo.md'
      - 'Material Theme Tutorial' : 'Material Theme Tutorial.md'